- name: Python
  logo: python
  url: https://www.python.org/
  color: 3C78A9
  logoColor: FFFFFF
  projects:
    - https://github.com/Abhay2611/SpaceInvaderGame
- name: JavaScript
  logo: javascript
  url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
  color: F1E05A
  logoColor: FFFFFF
  projects:
    - https://github.com/Abhay2611/covid-19-tracker
- name: Node.js
  logo: node.js
  url: https://nodejs.org/en/
  color: 47d147
  logoColor: FFFFFF
  projects:
    - https://github.com/Abhay2611/lcoMERNproj
- name: Vue
  logo: vue
  url: https://vuejs.org/v2/guide/
  color: 4FA1EF
  logoColor: FFFFFF
  projects:
    - https://github.com/Abhay2611/vue-todo
- name: HTML
  logo: HTML5
  url: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5
  color: ff751a
  logoColor: FFFFFF
  projects:
    - https://github.com/Abhay2611/web-portfolio